# Generated by Django 2.2.2 on 2019-07-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=60, null=True)),
                ('LAST_NAME', models.CharField(blank=True, max_length=60, null=True)),
                ('GENDER', models.CharField(blank=True, max_length=6, null=True)),
                ('DATE_OF_BIRTH', models.DateField(blank=True, null=True)),
                ('PHONE', models.IntegerField(blank=True, null=True)),
                ('MAIL_ID', models.EmailField(blank=True, max_length=100, null=True)),
                ('AFILATION', models.CharField(blank=True, max_length=60, null=True)),
                ('DEPARTMENT', models.CharField(blank=True, max_length=60, null=True)),
                ('FACEBOOK_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('TWITTER_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('GITHUB_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('SKILLS', models.CharField(blank=True, max_length=150, null=True)),
                ('LEVEL', models.CharField(blank=True, max_length=50, null=True)),
                ('EXPERIENCE', models.IntegerField(blank=True, null=True)),
                ('PORTFOLIO_URL', models.CharField(blank=True, max_length=300, null=True)),
                ('PORTFOLIO_FILES', models.FileField(blank=True, null=True, upload_to='media/')),
                ('REGISTERED_AT', models.DateTimeField(auto_now_add=True, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('student', 'Student'), ('student-teacher', 'Student-teacher'), ('professor', 'Professor')], default='registered', max_length=120, null=True)),
                ('REMARKS', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
