# Generated by Django 2.2.2 on 2019-07-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0003_user_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='OCCUPATION',
        ),
        migrations.AddField(
            model_name='user',
            name='STATUS',
            field=models.CharField(blank=True, choices=[('Pending', 'PENDING'), ('Checking', 'CHECKING'), ('Approved', 'APPROVED'), ('Rejected', 'REJECTED')], default='Pending', max_length=120, null=True),
        ),
    ]
