# Generated by Django 2.2.2 on 2019-08-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0006_auto_20190729_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='PORTFOLIO_FILES',
            new_name='port',
        ),
    ]
