# Generated by Django 2.2.2 on 2019-08-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0008_auto_20190801_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='PORTFOLIO_FILES',
        ),
        migrations.AddField(
            model_name='user',
            name='MIDDLE_NAME',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
