# Generated by Django 2.2.2 on 2019-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0009_auto_20190812_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='MIDDLE_NAME',
            field=models.CharField(max_length=61, null=True),
        ),
    ]
