# Generated by Django 2.2.2 on 2019-08-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0010_auto_20190813_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='molfujou',
        ),
    ]
