# Generated by Django 2.2.2 on 2019-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0011_auto_20190813_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molfujou',
            name='MIDDLE_NAME',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
