# Generated by Django 2.2.2 on 2019-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0014_auto_20190814_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NATIONALITY',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
