# Generated by Django 2.2.2 on 2019-08-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0016_auto_20190822_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='STATUS',
            field=models.CharField(blank=True, choices=[('Pending', 'PENDING'), ('Checking', 'CHECKING'), ('Approved', 'APPROVED'), ('Rejected', 'REJECTED')], max_length=120, null=True),
        ),
    ]
