# Generated by Django 2.2.2 on 2019-08-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0017_auto_20190822_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='STATUS',
            field=models.CharField(blank=True, choices=[('Checking', 'CHECKING'), ('Approved', 'APPROVED'), ('Rejected', 'REJECTED')], default='PENDING', max_length=10, null=True),
        ),
    ]
