# Generated by Django 2.2.2 on 2019-08-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0019_auto_20190823_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hackathon_Applicants',
            new_name='user',
        ),
    ]
