# Generated by Django 2.2.2 on 2019-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0021_auto_20190823_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='FIRST_NAME',
            new_name='名',
        ),
        migrations.AlterField(
            model_name='hackathon_applicants',
            name='STATUS',
            field=models.CharField(blank=True, choices=[('保留中', '保留中'), ('確認中', '確認中'), ('承認された', '承認された'), ('斥ける', '斥ける')], default='保留中', max_length=10, null=True),
        ),
    ]
