# Generated by Django 2.2.2 on 2019-08-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0022_auto_20190826_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='SKILLS',
            new_name='スキル',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='PORTFOLIO_URL',
            new_name='ポートフォリオ_URL',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='MIDDLE_NAME',
            new_name='ミドルネーム',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='MAIL_ID',
            new_name='メールID',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='LEVEL',
            new_name='レベル',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='REMARKS',
            new_name='備考',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='NATIONALITY',
            new_name='国籍',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='GENDER',
            new_name='性別',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='AFILATION',
            new_name='所属',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='UPDATED_AT',
            new_name='更新済み',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='STATUS',
            new_name='状態',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='DATE_OF_BIRTH',
            new_name='生年月日',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='REGISTERED_AT',
            new_name='登録済み',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='REMARKS_ADMIN',
            new_name='管理者の備考',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='EXPERIENCE',
            new_name='経験',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='DEPARTMENT',
            new_name='苗字',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='LAST_NAME',
            new_name='部署名',
        ),
        migrations.RenameField(
            model_name='hackathon_applicants',
            old_name='PHONE',
            new_name='電話',
        ),
    ]
